Video:
  Renderer: Vulkan
  Shader Mode: Async Recompiler (multi-threaded)
Audio:
  Renderer: Cubeb
Miscellaneous:
  Start games in fullscreen mode: true
  Exit RPCS3 when process finishes: true
  Pause emulation on RPCS3 focus loss: false
