OTA_HOST=10.0.2.2
OTA_INTERVAL=5
GRUBENV=/boot/efi/grub/grubenv
MODULES="e1000e af_packet vfat nls_cp437 nls_ascii virtio_pci virtio_gpu evdev uinput"
SYNC_DELAY=20
AUTO_INSTALL=0
AUTO_REBOOT=0
API_PORT=8080
SSH_PORT=2222
NIC=nic0
CONSOLE_PASSWORD=anyconsole
DEPLOY_HOST=ale
DEPLOY_PATH=anyconsole
