#!/usr/bin/env python3
import ctypes
import sdl2

sdl2.SDL_Init(sdl2.SDL_INIT_JOYSTICK)
text = ctypes.create_string_buffer(2 * ctypes.sizeof(sdl2.SDL_JoystickGUID) + 1)
sdl2.SDL_JoystickGetGUIDString(sdl2.SDL_JoystickGetDeviceGUID(0), text, len(text))
print(text.value.decode())
