#!/bin/sh
export TERM=linux
clear
echo "anyconsole slot $(otad slot)  boot $(cat /data/boots)"
for program in /opt/anyconsole/*; do
  [ -x "$program" ] && [ "$program" != /opt/anyconsole/main ] && "$program"
done
exec sh
