context.exec = [
  { path = "/bin/wireplumber" }
  { path = "/bin/pipewire-pulse" }
]

context.objects = [
  { factory = adapter
    args = {
      factory.name = support.null-audio-sink
      node.name = anyconsole_silence
      node.description = "No microphone"
      media.class = Audio/Source/Virtual
      node.virtual = true
      audio.position = [ MONO ]
    }
  }
]

context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "anyconsole microphone"
      audio.position = [ MONO ]
      filter.graph = {
        nodes = [
          { type = builtin label = sine name = @BLOW_NODE@ control = { Ampl = 0.0 } }
          { type = builtin label = mixer name = mix }
        ]
        links = [ { output = "@BLOW_NODE@:Out" input = "mix:In 2" } ]
        inputs = [ "mix:In 1" ]
        outputs = [ "mix:Out" ]
      }
      capture.props = { node.name = @MICROPHONE_NODE@_input node.passive = true }
      playback.props = { node.name = @MICROPHONE_NODE@ media.class = Audio/Source }
    }
  }
]
