wireplumber.settings = {
  device.routes.default-sink-volume = 1.0
  device.routes.default-source-volume = 1.0
}

wireplumber.components = [
  {
    name = device/find-detected-profile.lua, type = script/lua
    provides = hooks.device.profile.find-detected
  }
]

wireplumber.profiles = {
  main = {
    hooks.device.profile.find-detected = required
  }
}
