#!/bin/sh
set -eu
PICTURE_WIDTH=4
PICTURE_HEIGHT=3
VMU_PORTS="0 1 2 3"
cp -u /opt/redream/redream /engine/
find /bios -maxdepth 1 -type f -exec ln -sf {} /engine/ \;
for port in $VMU_PORTS; do ln -sf "/saves/vmu$port.bin" "/engine/vmu$port.bin"; done
height=${CANVAS#*x}
width=$((height * PICTURE_WIDTH / PICTURE_HEIGHT))
exec xwayland-run -geometry "${width}x$height" -- /engine/redream --width="$width" --height="$height" "$@"
